title: Îž Language
description: XY Language Documentation
theme: just-the-docs

url: https://doc.xy-lang.org

aux_links:
  XY on Github: https://github.com/xy-org/

liquid:
  error_mode: strict
  strict_filters: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Enable or disable heading anchors
heading_anchors: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Show navigation error report
nav_error_report: true # default is false/nil.

# don't like the way it looks
# logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/logo.svg"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
