name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build Docs with Jekyll
        run: bundle exec jekyll build
      - name: Build Tutorial with Jekyll
        run: bundle exec jekyll build
        working-directory: ./tutorial
      - name: Test Tutorial
        run: | # fuse is required by AppImage
          apt install libfuse3-3
          ./test
        working-directory: ./tutorial
